/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_sources__source_id__patch"];
        trace?: never;
    };
    "/api/sources/{source_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Source */
        post: operations["validate_source_api_sources__source_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Scan */
        post: operations["create_scan_api_sources__source_id__scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan Jobs */
        get: operations["get_scan_jobs_api_scans__scan_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CurrentJobRead */
        CurrentJobRead: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** External Id */
            external_id: string | null;
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Locations */
            locations: string[];
            /** Employment Type */
            employment_type: string | null;
            /** Posted Date */
            posted_date: string | null;
            /** Description Html */
            description_html: string | null;
            /** Description Text */
            description_text: string | null;
            /** Content Fingerprint */
            content_fingerprint: string;
            /** Raw Metadata */
            raw_metadata: {
                [key: string]: unknown;
            };
            /** Lifecycle Status */
            lifecycle_status: string;
            /** Consecutive Successful Absences */
            consecutive_successful_absences: number;
            /** Initial Import */
            initial_import: boolean;
            /**
             * First Discovered At
             * Format: date-time
             */
            first_discovered_at: string;
            /**
             * Last Observed At
             * Format: date-time
             */
            last_observed_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CurrentJobsPage */
        CurrentJobsPage: {
            /** Items */
            items: components["schemas"]["CurrentJobRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRead */
        JobRead: {
            /** Id */
            id: string;
            /** Scan Run Id */
            scan_run_id: string;
            /** Source Id */
            source_id: string;
            /** External Id */
            external_id: string | null;
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Locations */
            locations: string[];
            /** Employment Type */
            employment_type: string | null;
            /** Posted Date */
            posted_date: string | null;
            /** Description Html */
            description_html: string | null;
            /** Description Text */
            description_text: string | null;
            /** Content Fingerprint */
            content_fingerprint: string;
            /** Raw Metadata */
            raw_metadata: {
                [key: string]: unknown;
            };
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** JobsPage */
        JobsPage: {
            /** Items */
            items: components["schemas"]["JobRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ScanCreate */
        ScanCreate: {
            /**
             * Trigger
             * @default manual
             */
            trigger: string;
        };
        /** ScanRead */
        ScanRead: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Trigger */
            trigger: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Jobs Found */
            jobs_found: number;
            /** Jobs Persisted */
            jobs_persisted: number;
            /** Jobs Created */
            jobs_created: number;
            /** Jobs Updated */
            jobs_updated: number;
            /** Jobs Missing */
            jobs_missing: number;
            /** Pages Visited */
            pages_visited: number;
            /** Warnings */
            warnings: unknown[];
            /** Error Code */
            error_code: string | null;
            /** Error Diagnostics */
            error_diagnostics: {
                [key: string]: unknown;
            };
        };
        /** SourceCreate */
        SourceCreate: {
            /** Company */
            company: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** SourcePatch */
        SourcePatch: {
            /** Company */
            company?: string | null;
            /** Url */
            url?: string | null;
            /** Connector Config */
            connector_config?: {
                [key: string]: unknown;
            } | null;
        };
        /** SourceRead */
        SourceRead: {
            /** Id */
            id: string;
            /** Company */
            company: string;
            /** Url */
            url: string;
            /** Detected Platform */
            detected_platform: string | null;
            /** Connector Type */
            connector_type: string | null;
            /** Connector Config */
            connector_config: {
                [key: string]: unknown;
            };
            /** Detection */
            detection: {
                [key: string]: unknown;
            };
            /** Setup Status */
            setup_status: string;
            /** Health Status */
            health_status: string;
            /** Last Validation At */
            last_validation_at: string | null;
            /** Last Validation */
            last_validation: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationResponse */
        ValidationResponse: {
            source: components["schemas"]["SourceRead"];
            validation: components["schemas"]["ValidationResult"];
        };
        /** ValidationResult */
        ValidationResult: {
            /** Valid */
            valid: boolean;
            /** Setup Status */
            setup_status: string;
            /** Job Count */
            job_count?: number | null;
            /** Sample Jobs */
            sample_jobs?: {
                [key: string]: unknown;
            }[];
            /** Available Facets */
            available_facets?: {
                [key: string]: unknown;
            }[];
            /** Warnings */
            warnings?: {
                [key: string]: unknown;
            }[];
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"][];
                };
            };
        };
    };
    create_source_api_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_api_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_source_api_sources__source_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_api_sources__source_id__scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_jobs_api_scans__scan_id__jobs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                source_id?: string | null;
                lifecycle_status?: ("active" | "possibly_closed" | "closed") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentJobsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
